image: node:latest

stages:
  - build
  - test
  - pages

variables:
  NPM_CACHE_FOLDER: "$CI_PROJECT_DIR/.npm"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - node_modules

install:
  stage: build

  script:
    - npm ci

test:
  stage: test
  script:
    - npm run test

pages:
  stage: pages
  script:
    - npm run sprites
    - npm run build
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public